<?php
  $path=array(
      'AeroLAB'=>'img/prodotti/aero.png',
      'EasyOffice'=>'img/prodotti/eo.jpg',
      'Galileo'=>'img/prodotti/gl.png',
      'PhotoEdit'=>'img/prodotti/pe.jpg',
      'V.I.A.D.'=>'img/prodotti/viad.png',
      'VideoEdit'=>'img/prodotti/ve.jpg',
  );
  $path2=array(
    'Houston'=>'img/sedi/houston.jpg',
    'HoustonHQ'=>'img/sedi/houstonhq.jpg',
    'Moscow'=>'img/sedi/moscow.jpg',
    'MoscowHQ'=>'img/sedi/moscowhq.jpg',
    'Rome'=>'img/sedi/rome.jpg',
    'RomeHQ'=>'img/sedi/romehq.jpg',
    'Prague'=>'img/sedi/prague.jpg',
    'PragueHQ'=>'img/sedi/praguehq.jpg'
  )
?>